---
- name: Deploy chart
  hosts: localhost
  tasks:

    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Run Helm installation script
      command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm
      register: helm_install_result
      changed_when: false
      
    - name: Deploy latest version of moodle chart inside chart-test namespace
      kubernetes.core.helm:
        name: moodle
        chart_ref: oci://registry-1.docker.io/bitnamicharts/moodle
        release_namespace: chart-test
        create_namespace: true
